### ISSUE TITLE
Samba does not build manpages

### ISSUE THREAD

**Issue by RSully** [sjorge/pkgsrc-blackdot#5]
Just wanted to open an issue as a place for discussion about this.

**Comment by sjorge** [comment]
Probably best to file it here:
https://github.com/joyent/pkgsrc-wip 
or
http://www.pkgsrc.org/

I had a look at it a while ago but couldn't figure it out.

**Comment by sjorge** [comment]
I'm splitting off from the upstream one to simplify the Makefile the 2015Q4 packages. I will look at this again.

**Comment by sjorge** [comment]
It's fixed now in master, package will land in the 2015Q4 repo later today. It has been completely gutted and now only builds on SmartOS but more stuff is now working. Down to 3 patches that I will try to upstream.
