### ISSUE TITLE
Getting error compiling Samba on Omnios

### ISSUE THREAD

**Issue by FilipFrancis** [sjorge/pkgsrc-blackdot#6]
Hi Jorge,

I am trying to compile you samba on Omnios and it almost compiles completly but at the end with the docs 
getting following error:
[3683/3800] Generating manpages/smb.conf.5
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/xslt/man.xsl line 7 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
[3684/3800] Generating manpages/cifsdd.8
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd
file:///Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/build/DTD/samba-doc:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd"
 %DocBookDTD;
             ^
Entity: line 1: 
 %DocBookDTD; 
             ^
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/xslt/man.xsl line 7 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
[3685/3800] Generating manpages/dbwrap_tool.1
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd
file:///Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/build/DTD/samba-doc:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd"
 %DocBookDTD;
             ^
Entity: line 1: 
 %DocBookDTD; 
             ^
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/xslt/man.xsl line 7 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
[3686/3800] Generating manpages/eventlogadm.8
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd
file:///Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/build/DTD/samba-doc:19: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.2/docbookx.dtd"
 %DocBookDTD;
             ^
Entity: line 1: 
 %DocBookDTD; 
             ^
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/xslt/man.xsl line 7 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl

and this goes on and on
and then it fails
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl"
compilation error: file /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/docs-xml/xslt/man.xsl line 7 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl
Waf: Leaving directory `/Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd/work/samba-4.7.1/bin'
Build failed:
 -> task failed (err #5): 
        {task: manpages/smb.conf.5 smb.conf.5.xml,parameters.all.xml -> smb.conf.5}
 -> task failed (err #5): 
        {task: manpages/cifsdd.8 cifsdd.8.xml -> cifsdd.8}
 -> task failed (err #5): 
        {task: manpages/dbwrap_tool.1 dbwrap_tool.1.xml -> dbwrap_tool.1}
 -> task failed (err #5): 
        {task: manpages/eventlogadm.8 eventlogadm.8.xml -> eventlogadm.8}
 -> task failed (err #5): 
        {task: manpages/findsmb.1 findsmb.1.xml -> findsmb.1}
 -> task failed (err #5): 
        {task: manpages/libsmbclient.7 libsmbclient.7.xml -> libsmbclient.7}
 -> task failed (err #5): 
        {task: manpages/lmhosts.5 lmhosts.5.xml -> lmhosts.5}
 -> task failed (err #5): 
        {task: manpages/log2pcap.1 log2pcap.1.xml -> log2pcap.1}
 -> task failed (err #5): 
        {task: manpages/idmap_ad.8 idmap_ad.8.xml -> idmap_ad.8}
 -> task failed (err #5): 
        {task: manpages/idmap_autorid.8 idmap_autorid.8.xml -> idmap_autorid.8}
 -> task failed (err #5): 
        {task: manpages/idmap_hash.8 idmap_hash.8.xml -> idmap_hash.8}
 -> task failed (err #5): 
        {task: manpages/idmap_ldap.8 idmap_ldap.8.xml -> idmap_ldap.8}
 -> task failed (err #5): 
        {task: manpages/idmap_nss.8 idmap_nss.8.xml -> idmap_nss.8}
 -> task failed (err #5): 
        {task: manpages/idmap_rfc2307.8 idmap_rfc2307.8.xml -> idmap_rfc2307.8}
 -> task failed (err #5): 
        {task: manpages/idmap_rid.8 idmap_rid.8.xml -> idmap_rid.8}
 -> task failed (err #5): 
        {task: manpages/idmap_script.8 idmap_script.8.xml -> idmap_script.8}
 -> task failed (err #5): 
        {task: manpages/idmap_tdb.8 idmap_tdb.8.xml -> idmap_tdb.8}
 -> task failed (err #5): 
        {task: manpages/idmap_tdb2.8 idmap_tdb2.8.xml -> idmap_tdb2.8}
 -> task failed (err #5): 
        {task: manpages/mvxattr.1 mvxattr.1.xml -> mvxattr.1}
 -> task failed (err #5): 
        {task: manpages/net.8 net.8.xml -> net.8}
 -> task failed (err #5): 
        {task: manpages/nmbd.8 nmbd.8.xml -> nmbd.8}
 -> task failed (err #5): 
        {task: manpages/nmblookup.1 nmblookup.1.xml -> nmblookup.1}
 -> task failed (err #5): 
        {task: manpages/ntlm_auth.1 ntlm_auth.1.xml -> ntlm_auth.1}
 -> task failed (err #5): 
        {task: manpages/pdbedit.8 pdbedit.8.xml -> pdbedit.8}
 -> task failed (err #5): 
        {task: manpages/profiles.1 profiles.1.xml -> profiles.1}
 -> task failed (err #5): 
        {task: manpages/rpcclient.1 rpcclient.1.xml -> rpcclient.1}
 -> task failed (err #5): 
        {task: manpages/samba.7 samba.7.xml -> samba.7}
 -> task failed (err #5): 
        {task: manpages/samba.8 samba.8.xml -> samba.8}
 -> task failed (err #5): 
        {task: manpages/samba-tool.8 samba-tool.8.xml -> samba-tool.8}
 -> task failed (err #5): 
        {task: manpages/samba-regedit.8 samba-regedit.8.xml -> samba-regedit.8}
 -> task failed (err #5): 
        {task: manpages/sharesec.1 sharesec.1.xml -> sharesec.1}
 -> task failed (err #5): 
        {task: manpages/smbcacls.1 smbcacls.1.xml -> smbcacls.1}
 -> task failed (err #5): 
        {task: manpages/smbclient.1 smbclient.1.xml -> smbclient.1}
 -> task failed (err #5): 
        {task: manpages/smbcontrol.1 smbcontrol.1.xml -> smbcontrol.1}
 -> task failed (err #5): 
        {task: manpages/smbcquotas.1 smbcquotas.1.xml -> smbcquotas.1}
 -> task failed (err #5): 
        {task: manpages/smbd.8 smbd.8.xml -> smbd.8}
 -> task failed (err #5): 
        {task: manpages/smbget.1 smbget.1.xml -> smbget.1}
 -> task failed (err #5): 
        {task: manpages/smbgetrc.5 smbgetrc.5.xml -> smbgetrc.5}
 -> task failed (err #5): 
        {task: manpages/smbpasswd.5 smbpasswd.5.xml -> smbpasswd.5}
 -> task failed (err #5): 
        {task: manpages/smbpasswd.8 smbpasswd.8.xml -> smbpasswd.8}
 -> task failed (err #5): 
        {task: manpages/smbspool.8 smbspool.8.xml -> smbspool.8}
 -> task failed (err #5): 
        {task: manpages/smbspool_krb5_wrapper.8 smbspool_krb5_wrapper.8.xml -> smbspool_krb5_wrapper.8}
 -> task failed (err #5): 
        {task: manpages/smbstatus.1 smbstatus.1.xml -> smbstatus.1}
 -> task failed (err #5): 
        {task: manpages/smbtar.1 smbtar.1.xml -> smbtar.1}
 -> task failed (err #5): 
        {task: manpages/smbtree.1 smbtree.1.xml -> smbtree.1}
 -> task failed (err #5): 
        {task: manpages/testparm.1 testparm.1.xml -> testparm.1}
 -> task failed (err #5): 
        {task: manpages/vfs_acl_tdb.8 vfs_acl_tdb.8.xml -> vfs_acl_tdb.8}
 -> task failed (err #5): 
        {task: manpages/vfs_acl_xattr.8 vfs_acl_xattr.8.xml -> vfs_acl_xattr.8}
 -> task failed (err #5): 
        {task: manpages/vfs_aio_fork.8 vfs_aio_fork.8.xml -> vfs_aio_fork.8}
 -> task failed (err #5): 
        {task: manpages/vfs_aio_linux.8 vfs_aio_linux.8.xml -> vfs_aio_linux.8}
 -> task failed (err #5): 
        {task: manpages/vfs_aio_pthread.8 vfs_aio_pthread.8.xml -> vfs_aio_pthread.8}
 -> task failed (err #5): 
        {task: manpages/vfs_audit.8 vfs_audit.8.xml -> vfs_audit.8}
 -> task failed (err #5): 
        {task: manpages/vfs_btrfs.8 vfs_btrfs.8.xml -> vfs_btrfs.8}
 -> task failed (err #5): 
        {task: manpages/vfs_cacheprime.8 vfs_cacheprime.8.xml -> vfs_cacheprime.8}
 -> task failed (err #5): 
        {task: manpages/vfs_cap.8 vfs_cap.8.xml -> vfs_cap.8}
 -> task failed (err #5): 
        {task: manpages/vfs_catia.8 vfs_catia.8.xml -> vfs_catia.8}
 -> task failed (err #5): 
        {task: manpages/vfs_ceph.8 vfs_ceph.8.xml -> vfs_ceph.8}
 -> task failed (err #5): 
        {task: manpages/vfs_commit.8 vfs_commit.8.xml -> vfs_commit.8}
 -> task failed (err #5): 
        {task: manpages/vfs_crossrename.8 vfs_crossrename.8.xml -> vfs_crossrename.8}
 -> task failed (err #5): 
        {task: manpages/vfs_default_quota.8 vfs_default_quota.8.xml -> vfs_default_quota.8}
 -> task failed (err #5): 
        {task: manpages/vfs_dirsort.8 vfs_dirsort.8.xml -> vfs_dirsort.8}
 -> task failed (err #5): 
        {task: manpages/vfs_extd_audit.8 vfs_extd_audit.8.xml -> vfs_extd_audit.8}
 -> task failed (err #5): 
        {task: manpages/vfs_fake_perms.8 vfs_fake_perms.8.xml -> vfs_fake_perms.8}
 -> task failed (err #5): 
        {task: manpages/vfs_fileid.8 vfs_fileid.8.xml -> vfs_fileid.8}
 -> task failed (err #5): 
        {task: manpages/vfs_fruit.8 vfs_fruit.8.xml -> vfs_fruit.8}
 -> task failed (err #5): 
        {task: manpages/vfs_full_audit.8 vfs_full_audit.8.xml -> vfs_full_audit.8}
 -> task failed (err #5): 
        {task: manpages/vfs_glusterfs.8 vfs_glusterfs.8.xml -> vfs_glusterfs.8}
 -> task failed (err #5): 
        {task: manpages/vfs_gpfs.8 vfs_gpfs.8.xml -> vfs_gpfs.8}
 -> task failed (err #5): 
        {task: manpages/vfs_linux_xfs_sgid.8 vfs_linux_xfs_sgid.8.xml -> vfs_linux_xfs_sgid.8}
 -> task failed (err #5): 
        {task: manpages/vfs_media_harmony.8 vfs_media_harmony.8.xml -> vfs_media_harmony.8}
 -> task failed (err #5): 
        {task: manpages/vfs_netatalk.8 vfs_netatalk.8.xml -> vfs_netatalk.8}
 -> task failed (err #5): 
        {task: manpages/vfs_offline.8 vfs_offline.8.xml -> vfs_offline.8}
 -> task failed (err #5): 
        {task: manpages/vfs_prealloc.8 vfs_prealloc.8.xml -> vfs_prealloc.8}
 -> task failed (err #5): 
        {task: manpages/vfs_preopen.8 vfs_preopen.8.xml -> vfs_preopen.8}
 -> task failed (err #5): 
        {task: manpages/vfs_readahead.8 vfs_readahead.8.xml -> vfs_readahead.8}
 -> task failed (err #5): 
        {task: manpages/vfs_readonly.8 vfs_readonly.8.xml -> vfs_readonly.8}
 -> task failed (err #5): 
        {task: manpages/vfs_recycle.8 vfs_recycle.8.xml -> vfs_recycle.8}
 -> task failed (err #5): 
        {task: manpages/vfs_shadow_copy.8 vfs_shadow_copy.8.xml -> vfs_shadow_copy.8}
 -> task failed (err #5): 
        {task: manpages/vfs_shadow_copy2.8 vfs_shadow_copy2.8.xml -> vfs_shadow_copy2.8}
 -> task failed (err #5): 
        {task: manpages/vfs_shell_snap.8 vfs_shell_snap.8.xml -> vfs_shell_snap.8}
 -> task failed (err #5): 
        {task: manpages/vfs_snapper.8 vfs_snapper.8.xml -> vfs_snapper.8}
 -> task failed (err #5): 
        {task: manpages/vfs_streams_depot.8 vfs_streams_depot.8.xml -> vfs_streams_depot.8}
 -> task failed (err #5): 
        {task: manpages/vfs_streams_xattr.8 vfs_streams_xattr.8.xml -> vfs_streams_xattr.8}
 -> task failed (err #5): 
        {task: manpages/vfs_syncops.8 vfs_syncops.8.xml -> vfs_syncops.8}
 -> task failed (err #5): 
        {task: manpages/vfs_time_audit.8 vfs_time_audit.8.xml -> vfs_time_audit.8}
 -> task failed (err #5): 
        {task: manpages/vfs_tsmsm.8 vfs_tsmsm.8.xml -> vfs_tsmsm.8}
 -> task failed (err #5): 
        {task: manpages/vfs_unityed_media.8 vfs_unityed_media.8.xml -> vfs_unityed_media.8}
 -> task failed (err #5): 
        {task: manpages/vfs_worm.8 vfs_worm.8.xml -> vfs_worm.8}
 -> task failed (err #5): 
        {task: manpages/vfs_xattr_tdb.8 vfs_xattr_tdb.8.xml -> vfs_xattr_tdb.8}
 -> task failed (err #5): 
        {task: manpages/vfstest.1 vfstest.1.xml -> vfstest.1}
 -> task failed (err #5): 
        {task: manpages/wbinfo.1 wbinfo.1.xml -> wbinfo.1}
 -> task failed (err #5): 
        {task: manpages/winbindd.8 winbindd.8.xml -> winbindd.8}
 -> task failed (err #5): 
        {task: manpages/pam_winbind.8 pam_winbind.8.xml -> pam_winbind.8}
 -> task failed (err #5): 
        {task: manpages/pam_winbind.conf.5 pam_winbind.conf.5.xml -> pam_winbind.conf.5}
 -> task failed (err #5): 
        {task: manpages/winbind_krb5_locator.7 winbind_krb5_locator.7.xml -> winbind_krb5_locator.7}
gmake: *** [Makefile:8: all] Error 1
*** Error code 2

Stop.
bmake[1]: stopped in /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd
*** Error code 1

Stop.
bmake: stopped in /Pkgsrc/pkgsrc/pkgsrc-blackdot/samba-pbd

Any ideas
Regards
Filip

**Comment by sjorge** [comment]
What happens when you try and curl the URL's docbook is trying to fetch from sourceforge?
e.g. http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ?

**Comment by FilipFrancis** [comment]
Yes thats working
Filip

**Comment by FilipFrancis** [comment]
He you are working at UGENT.
I am from Deinze so not to far
Filip

**Comment by sjorge** [comment]
I'll try and setup a vm this weekend (If I don't forget/get distracted by other things).
It may be some docbook pkgsrc vs the one from OmniOS issue...

If you happen to go to FOSDEM next year, come and say high at the illumos booth, usually a few of us european user and some devs hang out there. (Myself will most likely only be there saturday though)

**Comment by FilipFrancis** [comment]
Well i was there this year with a collegue of mine.
and we are more and more doing or trying to do more stuff with Omnios 

Thanks for the help  would like to get this samba working as a full Domain controller.
My collegue and i have lots of ideas in getting stuff running on Illumos based distro.
We already have one customer testing some stuff on Omnios and we are trying to found some more things to get running on Omnios etc etc.
We are even in the middle of getting an other company up and running that will house all Free Open Source Software.
Regards and hope you have a solution that would be great.
And i will see you next year then at FOSDEM as we are going back to FOSDEM to check the latest and greatest things regarding Illumos
Filip

**Comment by sjorge** [comment]
Works fine for me on OmniOSce...

```
=> Creating /root/pkgsrc/pbd/samba-pbd/work/.smf_manifest.xml
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/.smf_manifest.xml /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/lib/svc/manifest/samba.xml
set -e ; cd /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/docs-xml/registry; for f in *.reg; do  /opt/local/bin/bsdinstall -c -o root -g root -m 644 ${f} /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/share/doc/samba-pbd/${f};  done
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/examples/LDAP/samba.schema  /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/share/examples/samba-pbd
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/examples/smb.conf.default  /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/share/examples/samba-pbd
mkdir -p /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/man/man{8,7,5,1}
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/docs/manpages/*.8  /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/man/man8
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/docs/manpages/*.7  /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/man/man7
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/docs/manpages/*.5  /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/man/man5
/opt/local/bin/bsdinstall -c -o root -g root -m 644 /root/pkgsrc/pbd/samba-pbd/work/samba-4.7.1/docs/manpages/*.1  /root/pkgsrc/pbd/samba-pbd/work/.destdir/opt/local/man/man1
=> Automatic manual page handling
=> Creating binary package /root/pkgsrc/pbd/samba-pbd/work/.packages/samba-pbd-4.7.1.tgz
===> Building binary package for samba-pbd-4.7.1
=> Creating binary package /root/pkgsrc/packages/All/samba-pbd-4.7.1.tgz
```
```
root@omnidev:~/pkgsrc/pbd/samba-pbd# uname -a
SunOS omnidev 5.11 omnios-r151024-c2a1589567 i86pc i386 i86pc
```

**Comment by sjorge** [comment]
```bash
#### Clean OmniOSce r151024 install ####
#################################
## install required headers
pkg install system/header developer/library/lint
## generate pkgsrc vulnerabilities file
pkg_admin -K /opt/local/pkg fetch-pkg-vulnerabilities
## samba dependencies (slow VM so not willing to compile them all)
pkgin -y in git-base gcc49 cwrappers digest gmake nbpatch pkgconf python27 py27-expat docbook-xsl libgcrypt popt gnutls
## clone pkgsrc
git clone https://github.com/joyent/pkgsrc.git
## checkout 2016Q4 branch (my additional packages are build against that)
## NOTE: next year I will build against 2018QX, people report running my packages on newer base images
cd pkgsrc
git checkout pkgsrc_2016Q4
## clone my repo in the correct place
# NOTE: we are still in pkgsrc/
git clone https://github.com/sjorge/pkgsrc-blackdot.git pbd
## build samba-pbd
cd pbd/samba-pbd/
bmake clean
bmake
bmake package
```

**Comment by FilipFrancis** [comment]
Ok I will try this 
indeed i am not using the pkgsrc_2016Q4
i will make a new pkgsrc and try to get it compiling again
thanks
for the help 
will keep you posted.
Still working for the moment in Brussels ;-)
Filip

**Comment by FilipFrancis** [comment]
Jorge,

Just tried you solution and indeed it works thanks for this
Now i can start building a Samba Domain Controller in my network
Great
Thanks
Filip

**Comment by sjorge** [comment]
It was probably picking up docbook-xsl from somewhere else.

I’ll close this issue now, feel free to open if you run into other problems.
